# 此程序使用turtle库绘制中国国旗（五星红旗），展示了图形绘制和数学计算的应用
import turtle as t    #导入python中的画画工具包
import math
width,height,x1,y1=960,640,1,1
t.setup(width,height,x1,y1)
t.title("五星红旗")
x,y=width/2/15,height/2/10
D,d=height/3,height/10
R,r=D/2,d/2
H,h=D*math.cos(18*math.pi/180),d*math.cos(18*math.pi/180)
t.bgcolor("red")
t.speed(10)

t.penup()
t.pensize(5)
t.forward(-10*x)
t.lt(90)
t.forward(5*y+R)
t.right(162)
t.color("yellow")
t.fillcolor("yellow")
t.begin_fill()
for i in range (5):
    t.forward(H)
    t.right(144)
t.end_fill()

t.penup()
t.color('green')
t.right(18)
t.forward(R)
t.lt(90)
t.forward(5*x)
t.lt(90)
t.forward(3*y)
t.lt(90+math.atan(3*y/(5*x))*180/math.pi)
t.forward(r)
t.right(162)
t.color('yellow')
t.fillcolor('yellow')
t.begin_fill()
for i in range(5):
    t.forward(h)
    t.right(144)
t.end_fill()

t.penup()
t.color('blue')
t.right(18)
t.forward(r)
t.right(90+math.atan(3*y/(5*x))*180/math.pi)
t.forward(2*y)
t.lt(90)
t.forward(2*x)
t.right(180-math.atan(y/(7*x))*180/math.pi)
t.forward(r)
t.right(162)
t.color('yellow')
t.fillcolor('yellow')
t.begin_fill()
for i in range(5):
    t.forward(h)
    t.right(144)
t.end_fill()

t.penup()
t.right(18)
t.pencolor('green')
t.forward(r)
t.right(90+math.atan(y/(x*7))*180/math.pi)
t.forward(3*y-r)
t.lt(18)
t.color('yellow')
t.fillcolor('yellow')
t.begin_fill()
for i in range(5):
    t.forward(h)
    t.right(144)
t.end_fill()

t.penup()
t.color('black')
t.right(18)
t.forward(r+2*y)
t.right(90)
t.forward(x*2)
t.right(math.atan(y*4/(x*5))*180/math.pi)
t.forward(r)
t.right(162)
t.color('yellow')
t.fillcolor('yellow')
t.begin_fill()
for i in range(5):
    t.forward(h)
    t.right(144)
t.end_fill()
t.hideturtle()
t.done()
